Repository tianocore/edk2, pull requests merged in 2024-11, with the labels that each got.

#6385 MdeModulePkg: SataControllerSupported checks DevicePath Protocol
  MdeModulePkg/Bus/Pci/SataControllerDxe/SataController.c
  MdeModulePkg/Bus/Pci/SataControllerDxe/SataController.h
  MdeModulePkg/Bus/Pci/SataControllerDxe/SataControllerDxe.inf
Labels: push

#6244 MdePkg: CodeQL Fixes.
  MdePkg/Include/IndustryStandard/PciExpress21.h
  MdePkg/Library/BaseLib/String.c
  MdePkg/Library/BasePeCoffLib/BasePeCoff.c
  MdePkg/Library/PeiServicesLib/PeiServicesLib.c
  MdePkg/Library/UefiDevicePathLib/DevicePathFromText.c
  MdePkg/Library/UefiDevicePathLib/DevicePathToText.c
  MdePkg/Library/UefiFileHandleLib/UefiFileHandleLib.c
  MdePkg/Library/UefiLib/Acpi.c
  MdePkg/Library/UefiLib/Console.c
  MdePkg/Library/UefiLib/UefiLibPrint.c
  MdePkg/Library/UefiPciSegmentLibPciRootBridgeIo/PciSegmentLib.c
Labels: push

#6274 UefiCpuPkg: Remove AMD 32-bit SMRAM save state map
  UefiCpuPkg/Library/MmSaveStateLib/AmdMmSaveState.c
  UefiCpuPkg/Library/SmmCpuFeaturesLib/AmdSmmCpuFeaturesLib.c
  UefiCpuPkg/Library/SmmRelocationLib/AmdSmramSaveStateConfig.c
Labels: push

#6389 CryptoPkg: Updated the missed architectures.
  CryptoPkg/Library/BaseCryptLib/PeiCryptLib.inf
Labels: push

#6402 UnitTestFrameworkPkg: Use TianoCore mirror of subhook submodule
  .gitmodules
  ReadMe.rst
  UnitTestFrameworkPkg/ReadMe.md
Labels: push

#6394 CryptoPkg: Increase ScratchMemory buffer for openssl 3.0.15
  CryptoPkg/Library/BaseCryptLib/SysCall/RuntimeMemAllocation.c
Labels: push, impact:security

#6388 CryptoPkg: Added MM_STANDALONE support in CryptoPkg.
  CryptoPkg/CryptoPkg.dsc
  CryptoPkg/Driver/CryptoStandaloneMm.c
  CryptoPkg/Driver/CryptoStandaloneMm.inf
  CryptoPkg/Library/BaseCryptLibOnProtocolPpi/StandaloneMmCryptLib.c
  CryptoPkg/Library/BaseCryptLibOnProtocolPpi/StandaloneMmCryptLib.inf
Labels: push

#6240 StandaloneMmPkg/MmIpl: Optimize hob pointer check flow
  StandaloneMmPkg/Drivers/StandaloneMmIplPei/MmFoundationHob.c
Labels: push

#6407 UnitTestFrameworkPkg: Use TianoCore mirror of subhook submodule
  .gitmodules
  ReadMe.rst
  UnitTestFrameworkPkg/ReadMe.md
Labels: push

#6418 CryptoPkg/BaseCryptLib: Fix serial number read overrun
  CryptoPkg/Library/BaseCryptLib/Pk/CryptX509.c
Labels: push, impact:security

#6421 MdePkg/Test/DevicePathLib: Remove FreePool(NULL)
  MdePkg/Test/UnitTest/Library/DevicePathLib/TestDevicePathLib.c
Labels: push, impact:security

#6419 UefiCpuPkg/MtrrLib: Fix unit test read overflow
  UefiCpuPkg/Library/MtrrLib/UnitTest/Support.c
Labels: push, impact:security

#6420 NetworkPkg/Dhcp6Dxe: Fix sanitizer issues
  NetworkPkg/Dhcp6Dxe/GoogleTest/Dhcp6IoGoogleTest.cpp
Labels: push, impact:security

#6435 * Maintainers.txt: add Linus Liu as a UefiPayloadPkg maintainer
  Maintainers.txt
Labels: push

#6282 [BZ-4860] FatPkg/FatPei: Simplify the GPT Header Check
  FatPkg/FatPei/Gpt.c
Labels: push, impact:testing

#6220 EmulatorPkg WinThunk.c: Use Win32 API to Query PerformanceFrequency and PerformanceCount
  EmulatorPkg/Win/Host/WinThunk.c
Labels: push

#6436 Maintainers.txt: update Leif's email address
  .mailmap
  Maintainers.txt
Labels: push

#6440 Maintainers.txt: Update M and R for UefiCpuPkg and StandaloneMmPkg
  Maintainers.txt
Labels: push

#6446 UefiCpuPkg: Fix unchecked returns and potential integer overflows V2
  UefiCpuPkg/CpuDxe/CpuMp.c
  UefiCpuPkg/CpuMpPei/CpuMpPei.c
  UefiCpuPkg/Library/CpuCommonFeaturesLib/MachineCheck.c
  UefiCpuPkg/Library/CpuExceptionHandlerLib/PeiCpuException.c
  UefiCpuPkg/Library/MpInitLib/AmdSev.c
  UefiCpuPkg/Library/MpInitLib/DxeMpInitLib.inf
  UefiCpuPkg/Library/MpInitLib/DxeMpLib.c
  UefiCpuPkg/Library/MpInitLib/MpLib.c
  UefiCpuPkg/Library/MpInitLib/MpLib.h
  UefiCpuPkg/Library/MpInitLib/PeiMpInitLib.inf
  UefiCpuPkg/Library/MpInitLib/PeiMpLib.c
  UefiCpuPkg/Library/MtrrLib/MtrrLib.c
  UefiCpuPkg/Library/RegisterCpuFeaturesLib/CpuFeaturesInitialize.c
  UefiCpuPkg/Library/RegisterCpuFeaturesLib/RegisterCpuFeaturesLib.c
  UefiCpuPkg/PiSmmCpuDxeSmm/MpService.c
  UefiCpuPkg/PiSmmCpuDxeSmm/PiSmmCpuDxeSmm.c
  UefiCpuPkg/PiSmmCpuDxeSmm/X64/PageTbl.c
  UefiCpuPkg/PiSmmCpuDxeSmm/X64/SmmFuncsArch.c
  UefiCpuPkg/UefiCpuPkg.dsc
Labels: push

#6404 MdePkg/SmmPciExpressLib: Ensure gBS variable for the constructor
  MdePkg/Library/SmmPciExpressLib/SmmPciExpressLib.inf
Labels: push

#6417 MdePkg/BaseRngLib: Remove global variable for RDRAND state update
  MdePkg/Library/BaseRngLib/Rand/RdRand.c
Labels: push

#6406 MdeModulePkg HobPrintLib: Add Guid to Guids section.
  MdeModulePkg/Library/HobPrintLib/HobPrintLib.inf
Labels: push

#6298 NetworkPkg: Restore TPL Before Return
  NetworkPkg/Ip6Dxe/Ip6Impl.c
  NetworkPkg/SnpDxe/Get_status.c
  NetworkPkg/SnpDxe/Transmit.c
Labels: push

#5968 ShellPkg: Fix copy-pasto in NULL check to prevent segfault
  ShellPkg/Application/Shell/ShellParametersProtocol.c
Labels: push

#6457 OvmfPkg/PlatformInitLib: enable x2apic mode if needed
  OvmfPkg/Library/PlatformInitLib/Platform.c
  OvmfPkg/Library/PlatformInitLib/PlatformInitLib.inf
Labels: push

#6409 CryptoPkg: Apply gettimeofday() solution to BaseCryptLibMbedTls
  CryptoPkg/Library/BaseCryptLibMbedTls/SysCall/ConstantTimeClock.c
  CryptoPkg/Library/BaseCryptLibMbedTls/SysCall/TimerWrapper.c
Labels: push

#6431 UefiCpuPkg/PiSmmCpuDxeSmm:Check resource HOB range before mapping
  UefiCpuPkg/PiSmmCpuDxeSmm/NonMmramMapStandaloneMm.c
Labels: push

#6439 SecurityPkg/Tcg2Config: Set TPM2.0 for default of Attempt TPM Device
  SecurityPkg/Tcg/Tcg2Config/Tcg2Config.vfr
Labels: push

#6468 .github: Handle deleted GitHub accounts
  .github/scripts/GitHub.py
Labels: push

#6472 ArmPlatformPkg: Allow up to 5 Secure Boot DB certs
  ArmPlatformPkg/SecureBootDefaultKeys.fdf.inc
Labels: push

#6478 EmbeddedPkg: reduce "Found ACPI table" messages from ERROR to INFO
  EmbeddedPkg/Library/AcpiLib/AcpiLib.c
Labels: push

#6403 OvmfPkg: Rerun dispatcher after initializing virtio-rng
  OvmfPkg/Library/PlatformBootManagerLib/BdsPlatform.c
Labels: push

#6479 ArmVirtPkg: Report an error if NETWORK_TLS_ENABLE is TRUE on ARM
  ArmVirtPkg/ArmVirt.dsc.inc
Labels: push

#6290 OvmfPkg/Library/HardwareInfoLib: Fix memory allocation at PciHostBridgeUtilityGetRootBridgesHostProvided
  OvmfPkg/Library/PciHostBridgeUtilityLib/PciHostBridgeUtilityLib.c
Labels: push
