Repository tianocore/edk2, pull requests merged in 2024-08, with the labels that each got.

#5924 Add PCI Express 6.0 Header Support
  MdePkg/Include/IndustryStandard/Pci.h
  MdePkg/Include/IndustryStandard/PciExpress21.h
  MdePkg/Include/IndustryStandard/PciExpress60.h
Labels: push

#6009 BaseTools/Scripts/BinToPcd.py: Update regex strings to use raw strings.
  BaseTools/Scripts/BinToPcd.py
Labels: push

#5935 IntelFsp2WrapperPkg/FspmWrapperPeim: Fix FspT/M address for measurement
  IntelFsp2WrapperPkg/FspmWrapperPeim/FspmWrapperPeim.c
  IntelFsp2WrapperPkg/FspmWrapperPeim/FspmWrapperPeim.inf
Labels: push

#6038 OvmfPkg: Pass correct virtio-scsi request size
  OvmfPkg/VirtioScsiDxe/VirtioScsi.c
Labels: push

#6027 BaseTools/WinRcPath: Improve Performance.
  BaseTools/Plugin/WindowsResourceCompiler/WinRcPath.py
Labels: push

#6030 MdePkg /IoRemappingTable: Define additional IORT SMMUv3 node flags.
  MdePkg/Include/IndustryStandard/IoRemappingTable.h
Labels: push

#5995 [BZ-4821] Support to Use Different Hash Algorithm for Capsule Payload Content
  BaseTools/Source/Python/Capsule/GenerateCapsule.py
Labels: push, impact:breaking-change, impact:testing

#6050 .github/request-reviews.yml: Use GitHub App authentication
  .github/workflows/request-reviews.yml
Labels: push

#6028 MdeModulePkg ConPlatform: Support IAD-style USB input devices.
  MdeModulePkg/Universal/Console/ConPlatformDxe/ConPlatform.c
Labels: push

#6011 MdePkg/BaseLib: Add CRC16 CCITT False Implementation.
  MdePkg/Include/Library/BaseLib.h
  MdePkg/Library/BaseLib/CheckSum.c
Labels: push

#5951 RedfishPkg: Allow deletion of the bootstrap account
  RedfishPkg/Include/Protocol/EdkIIRedfishCredential2.h
  RedfishPkg/RedfishCredentialDxe/RedfishCredentialDxe.c
  RedfishPkg/RedfishCredentialDxe/RedfishCredentialDxe.h
  RedfishPkg/RedfishCredentialDxe/RedfishCredentialDxe.inf
  RedfishPkg/RedfishHttpDxe/RedfishHttpData.h
  RedfishPkg/RedfishHttpDxe/RedfishHttpDxe.c
  RedfishPkg/RedfishHttpDxe/RedfishHttpDxe.h
  RedfishPkg/RedfishHttpDxe/RedfishHttpDxe.inf
  RedfishPkg/RedfishPkg.dec
Labels: push

#5954 NetworkPkg/DxeHttpLib: Support HTTP CONNECT message in Tx path.
  NetworkPkg/Library/DxeHttpLib/DxeHttpLib.c
Labels: push

#5806 MdeModulePkg/RamDiskDxe: fix memory leak.
  MdeModulePkg/Universal/Disk/RamDiskDxe/RamDiskImpl.c
Labels: push

#6083 .mergify: Fix pull_request_rules deprecation
  .mergify/config.yml
Labels: push

#6056 NetworkPkg: Improve GetBootFile() code flow
  NetworkPkg/HttpBootDxe/HttpBootImpl.c
  NetworkPkg/HttpBootDxe/HttpBootImpl.h
Labels: push

#6081 Allocate EfiACPIMemoryNVS buffer for TCG2 related usage in Tcg2ConfigPeim
  SecurityPkg/Tcg/Tcg2Config/Tcg2ConfigPeim.c
Labels: push

#6105 MdePkg: Define BrainpoolP512r1
  MdePkg/Include/IndustryStandard/Tpm20.h
Labels: push, impact:security

#6102 UefiCpuPkg: CpuPageTableLibTestHost: Disable Random Test Suite
  UefiCpuPkg/Library/CpuPageTableLib/UnitTest/CpuPageTableLibUnitTestHost.c
Labels: push, impact:testing

#5884 IntelFsp2Pkg: Correcting Data Region Length of MCUD section
  IntelFsp2Pkg/FspSecCore/SecFsp.c
  IntelFsp2Pkg/FspSecCore/X64/FspApiEntryT.nasm
Labels: push

#6121 Maintainers.txt: Remove Susovan Mohapatra
  Maintainers.txt
Labels: push

#6090 ArmPlatformPkg: Initialize Serial Port Before Writing
  ArmPlatformPkg/PrePeiCore/PrePeiCore.c
  ArmPlatformPkg/Sec/Sec.c
Labels: push

#6122 Maintainers.txt: Cleanup inactive maintainers.
  Maintainers.txt
Labels: push

#6117 OvmfPkg/LoongArchVirt: Clear the PGD series registers
  OvmfPkg/LoongArchVirt/Library/CpuMmuInitLib/CpuMmuInit.c
Labels: push

#6109 MdePkg/BaseFdtLib: Add FdtNodeOffsetByCompatible()
  MdePkg/Include/Library/FdtLib.h
  MdePkg/Library/BaseFdtLib/FdtLib.c
Labels: push

#6064 ShellPkg: Correct smbiosview strings and conditions for SMBIOS Type9
  ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.c
  ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/QueryTable.c
Labels: push

#6096 ArmPkg/GenericWatchdogDxe: Disable WDOG before the protocol installed
  ArmPkg/Drivers/GenericWatchdogDxe/GenericWatchdogDxe.c
Labels: push

#6088 CryptoPkg: Support BrainpoolP512r1 algorithm
  CryptoPkg/Include/Library/BaseCryptLib.h
  CryptoPkg/Library/BaseCryptLib/Pk/CryptEc.c
Labels: push, impact:security

#6112 OvmfPkg/PlatformInitLib: Reserve Sec Page Tables in TDVF
  OvmfPkg/Library/PlatformInitLib/IntelTdx.c
Labels: push

#6091 MdePkg:BaseArmTrngLibNull: Assert causing FVP stalling
  MdePkg/Library/BaseArmTrngLibNull/BaseArmTrngLibNull.c
Labels: push

#6089 MdeModulePkg: MAT Set RO/XP on Code/Data Sections Outside Image Memory
  MdeModulePkg/Core/Dxe/Misc/MemoryAttributesTable.c
Labels: push, impact:breaking-change

#6062 MdeModulePkg: Gcd: Only Update gMemoryMap Attributes if Correct GCD Type
  MdeModulePkg/Core/Dxe/Gcd/Gcd.c
Labels: push

#6034 MdeModulePkg NonDiscoverablePciDeviceIo: MMIO Memory XP By Default
  MdeModulePkg/Bus/Pci/NonDiscoverablePciDeviceDxe/NonDiscoverablePciDeviceIo.c
Labels: push

#6058 DynamicTablesPkg: AML code generation for IO resouce descriptor.
  DynamicTablesPkg/Include/Library/AmlLib/AmlLib.h
  DynamicTablesPkg/Library/Common/AmlLib/CodeGen/AmlResourceDataCodeGen.c
Labels: push

#6120 ArmVirtPkg: Drop incorrect reference to LzmaDecompressLib
  ArmVirtPkg/ArmVirtKvmTool.dsc
  ArmVirtPkg/ArmVirtQemuKernel.dsc
  ArmVirtPkg/ArmVirtXen.dsc
  ArmVirtPkg/PrePi/ArmVirtPrePiUniCoreRelocatable.inf
Labels: push

#5902 MdeModulePkg/VariableStandaloneMm: Fix TCG MOR secure feature issue
  MdeModulePkg/Universal/Variable/RuntimeDxe/PrivilegePolymorphic.h
  MdeModulePkg/Universal/Variable/RuntimeDxe/TcgMorLockSmm.c
  MdeModulePkg/Universal/Variable/RuntimeDxe/VariableStandaloneMm.c
  MdeModulePkg/Universal/Variable/RuntimeDxe/VariableTraditionalMm.c
Labels: push

#6084 EmbeddedPkg: Improve error handling in LocateAndInstallAcpiFromFvConditional
  EmbeddedPkg/Library/AcpiLib/AcpiLib.c
Labels: push

#6113 OvmfPkg: Refactor PcdSetNxForStack usage in TDVF
  OvmfPkg/Library/PeilessStartupLib/PeilessStartup.c
  OvmfPkg/Library/PlatformInitLib/Platform.c
  OvmfPkg/PlatformPei/IntelTdx.c
Labels: push

#6134 StandaloneMmPkg: Restart dispatcher once MM entry is registered for X64
  StandaloneMmPkg/StandaloneMmPkg.dec
Labels: push

#5829 OvmfPkg/PlatformInitLib: allow switching to 4-level paging
  OvmfPkg/Library/PlatformInitLib/MemDetect.c
  OvmfPkg/Library/PlatformInitLib/PlatformInitLib.inf
  OvmfPkg/Library/PlatformInitLib/X64/Paging.nasm
Labels: push

#6041 Sync AARCH64 GCD Capabilities with Page Table
  ArmPkg/Drivers/CpuDxe/CpuMmuCommon.c
Labels: push, impact:security

#6054 OvmfPkg: Move kernel hashes section to end
  OvmfPkg/ResetVector/X64/OvmfSevMetadata.asm
Labels: push

#6145 CryptoPkg/OpensslLib CLANGDWARF: Use gnu99 C dialect for asm() support
  CryptoPkg/Library/OpensslLib/OpensslLibAccel.inf
  CryptoPkg/Library/OpensslLib/OpensslLibFullAccel.inf
Labels: push

#6144 CryptoPkg/BaseCryptLibMbedTls: Fix uninitialized variable errors
  CryptoPkg/Library/BaseCryptLibMbedTls/Pk/CryptPkcs7Sign.c
  CryptoPkg/Library/BaseCryptLibMbedTls/Pk/CryptTs.c
Labels: push

#5833 BaseTools: Trim: Add header/footer for ASL include
  BaseTools/Source/Python/Trim/Trim.py
Labels: push, python

#6070 MdePkg: Remove duplicate source from BaseMemoryLib INF files
  MdePkg/Library/BaseMemoryLibMmx/BaseMemoryLibMmx.inf
  MdePkg/Library/BaseMemoryLibOptDxe/BaseMemoryLibOptDxe.inf
  MdePkg/Library/BaseMemoryLibOptPei/BaseMemoryLibOptPei.inf
  MdePkg/Library/BaseMemoryLibRepStr/BaseMemoryLibRepStr.inf
  MdePkg/Library/BaseMemoryLibSse2/BaseMemoryLibSse2.inf
Labels: push

#6006 SecurityPkg: Measure Invoke EBS even in failure case
  SecurityPkg/Tcg/Tcg2Dxe/Tcg2Dxe.c
Labels: push

#6086 SecurityPkg: Fix exponent unmarshaled as 16 bits
  SecurityPkg/Library/Tpm2CommandLib/Tpm2Object.c
Labels: push

#6127 MdePkg: Add Reset Reason definitions
  MdePkg/Include/IndustryStandard/Acpi65.h
Labels: push
