Repository tianocore/edk2, pull requests merged in 2024-09, with the labels that each got.

#5719 ArmPkg: Fix timer wrap-around
  ArmPkg/Library/ArmArchTimerLib/ArmArchTimerLib.c
Labels: push

#6151 MdeModulePkg/VariableStandaloneMm: Notify variable write ready in MM
  MdeModulePkg/Universal/Variable/RuntimeDxe/VariableStandaloneMm.c
  MdeModulePkg/Universal/Variable/RuntimeDxe/VariableStandaloneMm.inf
Labels: push

#6108 BaseTools: GenMake: Fix missing logs from GenMake.py
  BaseTools/Source/Python/AutoGen/GenMake.py
Labels: push

#6153 SecurityPkg: Fix break missing at TPM_ALG_KEYEDHASH case
  SecurityPkg/Library/Tpm2CommandLib/Tpm2Object.c
Labels: push

#6141 DynamicTablesPkg: Adds WSMT generator for X64
  DynamicTablesPkg/DynamicTables.dsc.inc
  DynamicTablesPkg/Include/AcpiTableGenerator.h
  DynamicTablesPkg/Include/X64NameSpaceObjects.h
  DynamicTablesPkg/Library/Acpi/X64/AcpiWsmtLib/AcpiWsmtLib.inf
  DynamicTablesPkg/Library/Acpi/X64/AcpiWsmtLib/WsmtGenerator.c
  DynamicTablesPkg/Library/Common/TableHelperLib/ConfigurationManagerObjectParser.c
  DynamicTablesPkg/Readme.md
Labels: push

#6040 DynamicTablesPkg: Adds generic ACPI Creator ID
  DynamicTablesPkg/Include/AcpiTableGenerator.h
  DynamicTablesPkg/Library/Acpi/Common/AcpiDbg2Lib/Dbg2Generator.c
  DynamicTablesPkg/Library/Acpi/Common/AcpiFadtLib/FadtGenerator.c
  DynamicTablesPkg/Library/Acpi/Common/AcpiMcfgLib/McfgGenerator.c
  DynamicTablesPkg/Library/Acpi/Common/AcpiPcctLib/PcctGenerator.c
  DynamicTablesPkg/Library/Acpi/Common/AcpiPpttLib/PpttGenerator.c
  DynamicTablesPkg/Library/Acpi/Common/AcpiRawLib/RawGenerator.c
  DynamicTablesPkg/Library/Acpi/Common/AcpiSpcrLib/SpcrGenerator.c
  DynamicTablesPkg/Library/Acpi/Common/AcpiSratLib/SratGenerator.c
  DynamicTablesPkg/Library/Acpi/Common/AcpiSsdtCpuTopologyLib/SsdtCpuTopologyGenerator.c
  DynamicTablesPkg/Library/Acpi/Common/AcpiSsdtPcieLib/SsdtPcieGenerator.c
  DynamicTablesPkg/Library/Acpi/Common/AcpiSsdtSerialPortLib/SsdtSerialPortGenerator.c
  DynamicTablesPkg/Library/Acpi/Common/AcpiTpm2Lib/Tpm2Generator.c
  DynamicTablesPkg/Library/Common/AmlLib/CodeGen/AmlCodeGen.c
Labels: push

#5901 NetworkPkg/SnpDxe: return error for unsupported parameter
  NetworkPkg/SnpDxe/Reset.c
Labels: push

#6073 FatPkg/EnhancedFatDxe: Downgrade debug level for no media found
  FatPkg/EnhancedFatDxe/Init.c
Labels: push

#6059 pip-requirements.txt: Bump versions of several packages and fix URL
  pip-requirements.txt
Labels: push

#3437 MdePkg: Fix a buffer overread.
  MdePkg/Library/UefiDevicePathLib/DevicePathToText.c
Labels: push

#6074 SecurityPkg: Optimization by moving PeiServicesLocatePpi outside loop
  SecurityPkg/FvReportPei/FvReportPei.c
Labels: push

#6022 NetworkPkg/WifiConnectionManagerDxe: Fix Wifi Connection Manager HII …
  NetworkPkg/WifiConnectionManagerDxe/WifiConnectionMgrHiiConfigAccess.c
Labels: push, impact:testing

#6114 OvmfPkg: Use TdHob instead of e820tables to get memory info in TDVF
  OvmfPkg/Library/PlatformInitLib/MemDetect.c
Labels: push

#6155 OvmfPkg/PlatformPei: Build gCcEventEntryHobGuid at First
  OvmfPkg/OvmfPkgIa32.dsc
  OvmfPkg/OvmfPkgIa32X64.dsc
  OvmfPkg/PlatformPei/IntelTdx.c
  OvmfPkg/PlatformPei/Platform.c
Labels: push

#6055 Update Return error macro
  MdePkg/Include/Base.h
Labels: push

#6045 Add Signature check and fix buffer overrun issue in FtwGetLastWriteHeader
  MdeModulePkg/Universal/FaultTolerantWriteDxe/FtwMisc.c
Labels: push, impact:security

#6157 ArmVirtPkg: Resolve RngLib via RngDxe for TRNG support
  ArmVirtPkg/ArmVirt.dsc.inc
Labels: push

#6104 MdeModulePkg: Add extra RestoreTpl() call in DiskIo and StartImage() to maintain TPL raise/restore symmetry
  MdeModulePkg/Core/Dxe/Image/Image.c
  MdeModulePkg/Universal/Disk/DiskIoDxe/DiskIo.c
Labels: push

#6147 ArmVirtPkg: Reorganize crypto dependencies
  ArmVirtPkg/ArmVirt.dsc.inc
  ArmVirtPkg/ArmVirtQemu.dsc
Labels: push

#6046 EmulatorPkg: fix X64 Unix/Host segfault with GCC toolchain profile
  EmulatorPkg/Unix/Host/Host.inf
Labels: push

#6033 XhciDxe: Fail the start of malfunctioning XHCI controllers
  MdeModulePkg/Bus/Pci/XhciDxe/Xhci.c
  MdeModulePkg/Bus/Pci/XhciDxe/XhciReg.c
  MdeModulePkg/Bus/Pci/XhciDxe/XhciSched.c
Labels: push

#6124 MdeModulePkg: UefiBootManagerLib: Update assert condition
  MdeModulePkg/Library/UefiBootManagerLib/BmBoot.c
Labels: push

#6093 EmbeddedPkg: Fix SetBootMode return value as specified in header file.
  EmbeddedPkg/Library/PrePiHobLib/Hob.c
Labels: push

#6150 BaseTools: Disable MSVC volatileMetadata for VS2019 and VS2022 for X64
  BaseTools/Conf/tools_def.template
Labels: push

#6148 MdePkg/IndustryStandard: Add definitions for IPMI Boot Progress Code
  MdePkg/Include/IndustryStandard/IpmiNetFnGroupExtension.h
Labels: push

#6136 MdeModulePkg/Core/Pei: Add error handling for Section Length
  MdeModulePkg/Core/Pei/FwVol/FwVol.c
Labels: push

#6166 UefiCpuPkg/PiSmmCpuDxeSmm: Avoid to access MCA_CAP if CPU does not su…
  UefiCpuPkg/PiSmmCpuDxeSmm/SmmProfile.c
Labels: push

#6171 NetworkPkg/DxeNetLib: Update misleading comment
  NetworkPkg/Library/DxeNetLib/DxeNetLib.c
Labels: push

#6162 BaseTools: Remove Pip BaseTools
  .pytool/CISettings.py
  BaseTools/BinPipWrappers/PosixLike/AmlToC
  BaseTools/BinPipWrappers/PosixLike/BPDG
  BaseTools/BinPipWrappers/PosixLike/BrotliCompress
  BaseTools/BinPipWrappers/PosixLike/DevicePath
  BaseTools/BinPipWrappers/PosixLike/Ecc
  BaseTools/BinPipWrappers/PosixLike/EfiRom
  BaseTools/BinPipWrappers/PosixLike/GenCrc32
  BaseTools/BinPipWrappers/PosixLike/GenDepex
  BaseTools/BinPipWrappers/PosixLike/GenFds
  BaseTools/BinPipWrappers/PosixLike/GenFfs
  BaseTools/BinPipWrappers/PosixLike/GenFv
  BaseTools/BinPipWrappers/PosixLike/GenFw
  BaseTools/BinPipWrappers/PosixLike/GenPatchPcdTable
  BaseTools/BinPipWrappers/PosixLike/GenSec
  BaseTools/BinPipWrappers/PosixLike/GenerateCapsule
  BaseTools/BinPipWrappers/PosixLike/LzmaCompress
  BaseTools/BinPipWrappers/PosixLike/LzmaF86Compress
  BaseTools/BinPipWrappers/PosixLike/PatchPcdValue
  BaseTools/BinPipWrappers/PosixLike/Pkcs7Sign
  BaseTools/BinPipWrappers/PosixLike/Rsa2048Sha256GenerateKeys
  BaseTools/BinPipWrappers/PosixLike/Rsa2048Sha256Sign
  BaseTools/BinPipWrappers/PosixLike/Split
  BaseTools/BinPipWrappers/PosixLike/TargetTool
  BaseTools/BinPipWrappers/PosixLike/TianoCompress
  BaseTools/BinPipWrappers/PosixLike/Trim
  BaseTools/BinPipWrappers/PosixLike/UPT
  BaseTools/BinPipWrappers/PosixLike/VfrCompile
  BaseTools/BinPipWrappers/PosixLike/VolInfo
  BaseTools/BinPipWrappers/PosixLike/build
  BaseTools/BinPipWrappers/PosixLike/posix_path_env.yaml
  BaseTools/BinPipWrappers/WindowsLike/AmlToC.bat
  BaseTools/BinPipWrappers/WindowsLike/BPDG.bat
  BaseTools/BinPipWrappers/WindowsLike/Ecc.bat
  BaseTools/BinPipWrappers/WindowsLike/GenDepex.bat
  BaseTools/BinPipWrappers/WindowsLike/GenFds.bat
  BaseTools/BinPipWrappers/WindowsLike/GenPatchPcdTable.bat
  BaseTools/BinPipWrappers/WindowsLike/GenerateCapsule.bat
  BaseTools/BinPipWrappers/WindowsLike/PatchPcdValue.bat
  BaseTools/BinPipWrappers/WindowsLike/Pkcs7Sign.bat
  BaseTools/BinPipWrappers/WindowsLike/Rsa2048Sha256GenerateKeys.bat
  BaseTools/BinPipWrappers/WindowsLike/Rsa2048Sha256Sign.bat
  BaseTools/BinPipWrappers/WindowsLike/Split.bat
  BaseTools/BinPipWrappers/WindowsLike/TargetTool.bat
  BaseTools/BinPipWrappers/WindowsLike/Trim.bat
  BaseTools/BinPipWrappers/WindowsLike/UPT.bat
  BaseTools/BinPipWrappers/WindowsLike/build.bat
  BaseTools/BinPipWrappers/WindowsLike/win_build_tools_path_env.yaml
  BaseTools/BuildEnv
  BaseTools/Scripts/PatchCheck.py
  BaseTools/Source/Python/README.md
  BaseTools/toolsetup.bat
  pip-requirements.txt
Labels: push, impact:breaking-change

#6182 ArmPkg/ArmPsciMpServices: GetProcessorInfo copies incorrect structure
  ArmPkg/Drivers/ArmPsciMpServicesDxe/ArmPsciMpServicesDxe.c
Labels: push

#6179 MdeModulePkg/VariableRuntimeDxe: Fix VariablePolicyProtocol PRODUCES
  MdeModulePkg/Universal/Variable/RuntimeDxe/VariableRuntimeDxe.inf
Labels: push

#6152 .pytool/EccCheck: Trim leading path to modified directory
  .pytool/Plugin/EccCheck/EccCheck.py
Labels: push

#6110 IntelFsp2Pkg: Support FSP API to save and restore page table
  IntelFsp2Pkg/FspSecCore/Fsp24SecCoreM.inf
  IntelFsp2Pkg/FspSecCore/FspSecCoreM.inf
  IntelFsp2Pkg/FspSecCore/Ia32/Fsp24ApiEntryM.nasm
  IntelFsp2Pkg/FspSecCore/Ia32/FspApiEntryM.nasm
  IntelFsp2Pkg/FspSecCore/X64/Fsp24ApiEntryM.nasm
  IntelFsp2Pkg/FspSecCore/X64/FspApiEntryM.nasm
  IntelFsp2Pkg/IntelFsp2Pkg.dec
  IntelFsp2Pkg/Library/BaseFspCommonLib/FspCommonLib.c
  IntelFsp2Pkg/Library/BaseFspSwitchStackLib/BaseFspSwitchStackLib.inf
  IntelFsp2Pkg/Library/BaseFspSwitchStackLib/Ia32/Stack.nasm
  IntelFsp2Pkg/Library/BaseFspSwitchStackLib/X64/Stack.nasm
Labels: push

#6131 StandaloneMmPkg/MmIpl: Correct unblocked memory regions attribute
  StandaloneMmPkg/Drivers/StandaloneMmIplPei/MmFoundationHob.c
Labels: push

#6170 NetworkPkg/UefiPxeBcDxe: Support Report Status Code in the UefiPxe driver.
  NetworkPkg/UefiPxeBcDxe/PxeBcBoot.c
  NetworkPkg/UefiPxeBcDxe/PxeBcImpl.c
  NetworkPkg/UefiPxeBcDxe/PxeBcImpl.h
  NetworkPkg/UefiPxeBcDxe/UefiPxeBcDxe.inf
Labels: push, impact:breaking-change

#6178 NetworkPkg/MnpDxe: Convert TX buffer allocation messages to DEBUG_VERBOSE
  NetworkPkg/MnpDxe/MnpConfig.c
Labels: push

#6076 [BZ-4831] MdeModulePkg/DxeCapsuleLibFmp: Change the Event Notify to Cache ESRT Table
  MdeModulePkg/Library/DxeCapsuleLibFmp/DxeCapsuleLib.c
  MdeModulePkg/Library/DxeCapsuleLibFmp/DxeCapsuleRuntime.c
  MdeModulePkg/Library/DxeCapsuleLibFmp/DxeRuntimeCapsuleLib.inf
Labels: push, impact:breaking-change, impact:testing

#6168 BaseMemoryLib : Refactor SetMemWrapper to reduce binary size
  MdePkg/Library/BaseMemoryLib/BaseMemoryLib.inf
  MdePkg/Library/BaseMemoryLib/SetMemNWrapper.c
  MdePkg/Library/BaseMemoryLib/SetMemWrapper.c
  MdePkg/Library/BaseMemoryLibMmx/BaseMemoryLibMmx.inf
  MdePkg/Library/BaseMemoryLibMmx/SetMemNWrapper.c
  MdePkg/Library/BaseMemoryLibMmx/SetMemWrapper.c
  MdePkg/Library/BaseMemoryLibOptDxe/BaseMemoryLibOptDxe.inf
  MdePkg/Library/BaseMemoryLibOptDxe/SetMemNWrapper.c
  MdePkg/Library/BaseMemoryLibOptDxe/SetMemWrapper.c
  MdePkg/Library/BaseMemoryLibOptPei/BaseMemoryLibOptPei.inf
  MdePkg/Library/BaseMemoryLibOptPei/SetMemNWrapper.c
  MdePkg/Library/BaseMemoryLibOptPei/SetMemWrapper.c
  MdePkg/Library/BaseMemoryLibRepStr/BaseMemoryLibRepStr.inf
  MdePkg/Library/BaseMemoryLibRepStr/SetMemNWrapper.c
  MdePkg/Library/BaseMemoryLibRepStr/SetMemWrapper.c
  MdePkg/Library/BaseMemoryLibSse2/BaseMemoryLibSse2.inf
  MdePkg/Library/BaseMemoryLibSse2/SetMemNWrapper.c
  MdePkg/Library/BaseMemoryLibSse2/SetMemWrapper.c
  MdePkg/Library/UefiMemoryLib/SetMemNWrapper.c
  MdePkg/Library/UefiMemoryLib/SetMemWrapper.c
  MdePkg/Library/UefiMemoryLib/UefiMemoryLib.inf
Labels: push

#6177 MdePkg/IpmiNetFnGroupExtension.h: Enforce structure alignment
  MdePkg/Include/IndustryStandard/IpmiNetFnGroupExtension.h
Labels: push

#6106 MdeModulePkg: Enable Data Terminal at end of serial
  MdeModulePkg/Universal/Console/TerminalDxe/TerminalConIn.c
Labels: push

#6125 MdeModulePkg: Fix buffer overflow in MergeMemoryMap
  MdeModulePkg/Core/Dxe/Misc/MemoryAttributesTable.c
Labels: push

#6193 MdePkg DebugLib: Enable FILE NAME as DEBUG ASSERT for GCC12
  MdePkg/Include/Library/DebugLib.h
Labels: push

#6199 OvmfPkg/RiscVVirtQemu: Remove non-needed !include line
  OvmfPkg/RiscVVirt/RiscVVirt.dsc.inc
Labels: push

#6133 OvmfPkg: Use TdInfo instead of fw_cfg to get cpu count in TDVF
  OvmfPkg/Library/PlatformInitLib/Platform.c
  OvmfPkg/Library/PlatformInitLib/PlatformInitLib.inf
  OvmfPkg/OvmfPkgIa32.dsc
Labels: push

#6138 OvmfPkg/CpuHotplugSmm: delay SMM exit
  OvmfPkg/CpuHotplugSmm/CpuHotplug.c
Labels: push

#6202 NetworkPkg/HttpBootDxe: Correctly uninstall HttpBootCallbackProtocol
  NetworkPkg/HttpBootDxe/HttpBootImpl.c
Labels: push

#6205 ArmPkg: Avoid building ArmCrashDumpDxe on ARM
  ArmPkg/ArmPkg.dsc
Labels: push

#6174 RedfishPkg/Include: move protocol version definition to protocol header
  RedfishPkg/Include/Protocol/EdkIIRedfishPlatformConfig.h
  RedfishPkg/RedfishPlatformConfigDxe/RedfishPlatformConfigDxe.h
Labels: push

#6203 UefiPayloadPkg: Move FADT check to consumer coode.
  UefiPayloadPkg/Library/AcpiTimerLib/AcpiTimerLib.c
  UefiPayloadPkg/Library/ResetSystemLib/ResetSystemLib.c
  UefiPayloadPkg/UefiPayloadEntry/AcpiTable.c
Labels: push

#6180 UefiCpuPkg/AmdSmmCpuFeaturesLib: Skip SMBASE configuration
  UefiCpuPkg/Library/SmmCpuFeaturesLib/AmdSmmCpuFeaturesLib.c
  UefiCpuPkg/Library/SmmCpuFeaturesLib/AmdSmmCpuFeaturesLib.inf
Labels: push

#6206 Maintainers: Remove Ard Biesheuvel from all packages
  Maintainers.txt
Labels: push

#6207 BaseTools/tools_def ARM: Disable stack protector with CLANGDWARF
  BaseTools/Conf/tools_def.template
Labels: push

#6217 Maintainers.txt: Add Sami Mujawar as maintainer for Arm modules
  Maintainers.txt
Labels: push

#6173 UefiCpuPkg/MtrrLib: MtrrLibIsMtrrSupported always return FALSE in TD-…
  UefiCpuPkg/Library/MtrrLib/MtrrLib.c
Labels: push

#6215 Set Serial Clockrate based on data parsed from host firmware
  UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.c
  UefiPayloadPkg/UefiPayloadEntry/UefiPayloadEntry.inf
Labels: push

#6219 BaseTools: Update RETURN_ERROR Macro in BaseTypes.h
  BaseTools/Source/C/Include/Common/BaseTypes.h
Labels: push

#6232 UefiPayloadPkg: Add LOCKBOX_SUPPORT in UPL and set it as FALSE in def…
  UefiPayloadPkg/UefiPayloadPkg.dsc
Labels: push

#6216 BaseTools: Fix multiple 'invalid escape sequence' warnings in tests
  BaseTools/Source/Python/Ecc/Check.py
  BaseTools/Source/Python/Ecc/Configuration.py
  BaseTools/Source/Python/Ecc/MetaFileWorkspace/MetaFileParser.py
  BaseTools/Source/Python/Ecc/c.py
  BaseTools/Source/Python/Eot/EotGlobalData.py
  BaseTools/Source/Python/Eot/c.py
  BaseTools/Source/Python/UPT/Library/CommentParsing.py
  BaseTools/Source/Python/UPT/Library/ExpressionValidate.py
  BaseTools/Source/Python/UPT/Library/Misc.py
  BaseTools/Source/Python/UPT/Library/StringUtils.py
  BaseTools/Source/Python/UPT/Parser/DecParserMisc.py
  BaseTools/Source/Python/UPT/Parser/InfAsBuiltProcess.py
  BaseTools/Source/Python/UPT/Parser/InfDefineSectionParser.py
  BaseTools/Source/Python/UPT/Parser/InfParserMisc.py
  BaseTools/Source/Python/UPT/PomAdapter/DecPomAlignment.py
  BaseTools/Source/Python/UPT/Xml/IniToXml.py
  BaseTools/Source/Python/UPT/Xml/PcdXml.py
  BaseTools/Source/Python/UPT/Xml/XmlParser.py
Labels: push

#6231 UefiPayloadPkg: Enhance ReadMe.md for ELF and FIT
  UefiPayloadPkg/Readme.md
Labels: push

#6042 FatPkg: Improvements to Fat to Fix File Corruption
  FatPkg/EnhancedFatDxe/DiskCache.c
  FatPkg/EnhancedFatDxe/Fat.h
  FatPkg/EnhancedFatDxe/Init.c
  FatPkg/FatPkg.ci.yaml
Labels: push

#6200 ShellPkg: add missing linefeed in reset message
  ShellPkg/Library/UefiShellLevel2CommandsLib/Reset.c
Labels: push

#6204 ArmVirtPkg: Correct PcdDxeNxMemoryProtectionPolicy comment
  ArmVirtPkg/ArmVirt.dsc.inc
Labels: push

#6241 DynamicTablesPkg/FdtHwInfoParserLib: add missing resolutions/includes
  DynamicTablesPkg/Library/FdtHwInfoParserLib/Arm/BootArch/ArmBootArchParser.c
  DynamicTablesPkg/Library/FdtHwInfoParserLib/Arm/GenericTimer/ArmGenericTimerParser.c
  DynamicTablesPkg/Library/FdtHwInfoParserLib/Arm/Gic/ArmGicDParser.c
  DynamicTablesPkg/Library/FdtHwInfoParserLib/Arm/Gic/ArmGicItsParser.c
  DynamicTablesPkg/Library/FdtHwInfoParserLib/Arm/Gic/ArmGicMsiFrameParser.c
  DynamicTablesPkg/Library/FdtHwInfoParserLib/Arm/Gic/ArmGicRParser.c
  DynamicTablesPkg/Library/FdtHwInfoParserLib/FdtHwInfoParserLib.inf
  DynamicTablesPkg/Library/FdtHwInfoParserLib/FdtUtility.c
  DynamicTablesPkg/Library/FdtHwInfoParserLib/Pci/PciConfigSpaceParser.c
  DynamicTablesPkg/Library/FdtHwInfoParserLib/Serial/SerialPortParser.c
Labels: push

#6247 .pytool/UncrustifyCheck: Show errors in output
  .pytool/Plugin/UncrustifyCheck/UncrustifyCheck.py
Labels: push

#6172 IntelFsp2Pkg : Refactor BaseFspCommonLib to reduce binary size
  IntelFsp2Pkg/Library/BaseFspCommonLib/BaseFspCommonLib.inf
  IntelFsp2Pkg/Library/BaseFspCommonLib/FspCommonLib.c
  IntelFsp2Pkg/Library/BaseFspCommonLib/ReturnStatus.c
Labels: push

#6255 .gitignore: Ignore Python venv files
  .gitignore
Labels: push

#6249 MdePkg: Fix overflow issue in BasePeCoffLib: PeCoffLoaderRelocateImage
  MdePkg/Library/BasePeCoffLib/BasePeCoff.c
Labels: push, impact:security
