Repository tianocore/edk2, pull requests merged in 2024-07, with the labels that each got.

#5832 .pytool: CompilerPlugin: Pass through build vars
  .pytool/Plugin/CompilerPlugin/CompilerPlugin.py
Labels: push, python

#5794 MdeModulePkg/UsbBusDxe: USB issue fix when the port reset
  MdeModulePkg/Bus/Usb/UsbBusDxe/UsbBus.c
Labels: push

#5825 DscCompleteCheck: Allow git ignore syntax
  .pytool/Plugin/DscCompleteCheck/DscCompleteCheck.py
  .pytool/Plugin/DscCompleteCheck/Readme.md
Labels: push, python

#5467 BaseTools: InfBuildData: Fix Private value retrieval
  BaseTools/Source/Python/Workspace/InfBuildData.py
Labels: push, python

#5793 Nvme u64 format fix
  MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpress.c
Labels: push

#5830 AmdSev: enable kernel hashes without initrd
  OvmfPkg/AmdSev/BlobVerifierLibSevHashes/BlobVerifierSevHashes.c
Labels: push

#5852 MdePkg/Nvme.h: Add missing NVMe capability descriptions
  MdePkg/Include/IndustryStandard/Nvme.h
Labels: push

#5845 EmbeddedPkg/VirtualRealTimeClockLib: Support SOURCE_DATE_EPOCH
  EmbeddedPkg/Library/VirtualRealTimeClockLib/VirtualRealTimeClockLib.inf
Labels: push

#5871 SecurityPkg/Tcg2Config: Cast pointer type to VOID* to avoid potential build error.
  SecurityPkg/Tcg/Tcg2Config/Tcg2ConfigPeim.c
Labels: push, impact:breaking-change

#5828 MdePkg/Tdx.h: Fix the order of NumVcpus and MaxVcpus
  MdePkg/Include/IndustryStandard/Tdx.h
Labels: push

#5864 UefiCpuPkg/PiSmmCpuDxeSmm: Fix system hang when SmmProfile enable
  UefiCpuPkg/PiSmmCpuDxeSmm/SmmProfile.c
Labels: push

#5848 StandaloneMmPkg: Fix section data length returned larger than actual size
  StandaloneMmPkg/Include/Library/FvLib.h
  StandaloneMmPkg/Library/FvLib/FvLib.c
Labels: push, impact:breaking-change, impact:security

#5873 OvmfPkg/LoongArchVirt: Optimize the use of serial port libraries
  OvmfPkg/LoongArchVirt/LoongArchVirtQemu.dsc
Labels: push

#5799 BaseTools: Add VS2022 support.
  BaseTools/Conf/tools_def.template
  BaseTools/Plugin/WindowsVsToolChain/WindowsVsToolChain.py
  BaseTools/set_vsprefix_envs.bat
  BaseTools/toolsetup.bat
  edksetup.bat
Labels: push

#5894 BaseTools: change non-ASCII characters in LinuxGcc5ToolChain.py
  BaseTools/Plugin/LinuxGcc5ToolChain/LinuxGcc5ToolChain.py
Labels: push

#5889 FmpDevicePkg: Correct broken Depex in FmpDxe
  FmpDevicePkg/FmpDxe/FmpDxe.inf
Labels: push

#5859 MdeModulePkg: Remove PeiAllocatePool() Assert
  MdeModulePkg/Core/Pei/Memory/MemoryServices.c
Labels: push

#5897 RedfishPkg/RedfishPlatformConfigDxe: remove false alarm
  RedfishPkg/RedfishPlatformConfigDxe/RedfishPlatformConfigDxe.c
Labels: push

#5896 BaseTools/Ecc: Allow `static` as a modifier
  BaseTools/Source/Python/Ecc/config.ini
Labels: push

#5895 .github: Update pull_request_template.md
  .github/pull_request_template.md
Labels: push

#5874 OvmfPkg/Sec: Skip setup MTRR early in TD-Guest
  OvmfPkg/IntelTdx/Sec/SecMain.c
  OvmfPkg/Sec/SecMain.c
Labels: push

#5899 NetworkPkg/HttpDxe: Track HttpInstance URL buffer length.
  NetworkPkg/HttpDxe/HttpImpl.c
  NetworkPkg/HttpDxe/HttpProto.c
  NetworkPkg/HttpDxe/HttpProto.h
Labels: push

#5860 MdeModulePkg/RuntimeResetSystemLib: Make global static
  MdeModulePkg/Library/RuntimeResetSystemLib/RuntimeResetSystemLib.c
Labels: push

#5861 MdePkg/StmApi.h: Add SMM_REV_ID definition for STM header
  MdePkg/Include/Register/Intel/StmApi.h
Labels: push

#5878 IntelFsp2WrapperPkg: FSP measurement based on PcdFspMeasurementConfig
  IntelFsp2WrapperPkg/IntelFsp2WrapperPkg.dec
Labels: push

#5900 OvmfPkgX64: Set default value of CC_MEASUREMENT_ENABLE to TRUE
  OvmfPkg/IntelTdx/README.md
  OvmfPkg/OvmfPkgX64.dsc
Labels: push

#5903 UefiPayloadPkg:Modify the PCD PcieResizableBar to dynamic PCD
  UefiPayloadPkg/UefiPayloadPkg.dsc
Labels: push

#5868 SecurityPkg/Tcg2Acpi: Revise debug print
  SecurityPkg/Tcg/Tcg2Acpi/Tcg2Acpi.c
Labels: push

#5910 OvmfPkg: Add network support for LoongArch QEMU platform
  OvmfPkg/LoongArchVirt/LoongArchVirtQemu.dsc
  OvmfPkg/LoongArchVirt/LoongArchVirtQemu.fdf
Labels: push

#5898 BaseTools: Ecc disable ascii scan
  BaseTools/Source/Python/Ecc/Check.py
  BaseTools/Source/Python/Ecc/Configuration.py
  BaseTools/Source/Python/Ecc/EccToolError.py
  BaseTools/Source/Python/Ecc/config.ini
Labels: push

#5905 BaseTools/HostBasedUnitTestRunner: Promote Unittest error to CI fail.
  BaseTools/Plugin/HostBasedUnitTestRunner/HostBasedUnitTestRunner.py
Labels: push, python, impact:breaking-change

#5909 BaseTools/CodeQL: Removed unused static function query
  BaseTools/Plugin/CodeQL/CodeQlQueries.qls
Labels: push

#5917 MdePkg/UefiDebugLibDebugPortProtocol: ExitBootServicesCallback() static
  MdePkg/Library/UefiDebugLibDebugPortProtocol/DebugLibConstructor.c
Labels: push

#5856 MdeModulePkg/SmiHandlerProfileInfo: Declare correct XML encoding
  MdeModulePkg/Application/SmiHandlerProfileInfo/SmiHandlerProfileInfo.c
Labels: push

#5918 RedfishPkg: Reduce DEBUG_ERROR to DEBUG_MANAGEABILITY in various places
  RedfishPkg/RedfishConfigHandler/RedfishConfigHandlerDriver.c
  RedfishPkg/RedfishDiscoverDxe/RedfishDiscoverDxe.c
Labels: push

#5881 [BZ-4653] MdeModulePkg/Core/DxeIplPeim: Enhance Code in DxeIplFindDxeCore Function
  MdeModulePkg/Core/DxeIplPeim/DxeLoad.c
Labels: push, impact:security, impact:testing

#5912 MdePkg: Define SMBIOS Protocol header according IndustryStandard
  MdePkg/Include/Protocol/Smbios.h
Labels: push

#5622 MdePkg: Added support for Smbios 3.7.0 Spec
  MdePkg/Include/IndustryStandard/SmBios.h
Labels: push, stale

#5870 [BZ-4655] MdeModulePkg/UfsBlockIoPei: Wait fDeviceInit Be Cleared by Devices
  MdeModulePkg/Bus/Ufs/UfsBlockIoPei/UfsBlockIoPei.c
  MdeModulePkg/Bus/Ufs/UfsBlockIoPei/UfsBlockIoPei.h
  MdeModulePkg/Bus/Ufs/UfsBlockIoPei/UfsHci.c
Labels: push, impact:testing

#5915 MdePkg/BaseLib: Optimize LOONGARCH64 csr usage
  MdePkg/Library/BaseLib/LoongArch64/AsmCsr.S
  MdePkg/Library/BaseLib/LoongArch64/Csr.c
Labels: push

#5919 MdeModulePkg: DxeCore: Fix Use-After-Free guard causing page fault
  MdeModulePkg/Core/Dxe/Mem/HeapGuard.c
Labels: push

#5836 .pytool/Plugin: Improve plugin log messages
  .pytool/Plugin/DependencyCheck/DependencyCheck.py
  .pytool/Plugin/SpellCheck/SpellCheck.py
  .pytool/Plugin/UncrustifyCheck/UncrustifyCheck.py
Labels: push

#5857 MdeModulePkg/SmiHandlerProfileInfo: Include profile in profile
  MdeModulePkg/Core/PiSmmCore/SmiHandlerProfile.c
Labels: push

#5927 ArmPlatformPkg: Update LcdHwNullLib to Prevent Init
  ArmPlatformPkg/Library/LcdHwNullLib/LcdHwNullLib.c
Labels: push

#5929 MdeModulePkg/VariablePolicyLib: Use wildcard character constant
  MdeModulePkg/Library/VariablePolicyLib/VariablePolicyLib.c
Labels: push

#5944 EmbeddedPkg: Mark DMA Memory Allocations XP By Default
  EmbeddedPkg/Library/NonCoherentDmaLib/NonCoherentDmaLib.c
Labels: push

#5942 ArmVirtPkg: QemuVirtMemInfoPeiLib: Allow PcdSystemMemorySize to be non-fixed
  ArmVirtPkg/Library/QemuVirtMemInfoLib/QemuVirtMemInfoPeiLib.inf
Labels: push

#5620 ShellPkg: Changes to print Type17 in Smbiosview
  ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.c
Labels: push

#5937 UefiCpuPkg: Revert "UefiCpuPkg/PiSmmCpuDxeSmm:Map SMRAM in 4K..."
  UefiCpuPkg/PiSmmCpuDxeSmm/SmmCpuMemoryManagement.c
Labels: push

#5747 ShellPkg/Acpiview: Add HEST Parser
  ShellPkg/Library/UefiShellAcpiViewCommandLib/AcpiParser.h
  ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Hest/HestParser.c
  ShellPkg/Library/UefiShellAcpiViewCommandLib/UefiShellAcpiViewCommandLib.c
  ShellPkg/Library/UefiShellAcpiViewCommandLib/UefiShellAcpiViewCommandLib.inf
Labels: push

#5922 ArmPkg: Remove Deprecated ArmPsciResetSystemLib
  ArmPkg/ArmPkg.dsc
  ArmPkg/Library/ArmPsciResetSystemLib/ArmPsciResetSystemLib.c
  ArmPkg/Library/ArmPsciResetSystemLib/ArmPsciResetSystemLib.inf
Labels: push, impact:breaking-change

#5934 ShellPkg: Support parser of MADT for LoongArch64
  ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Madt/MadtParser.c
Labels: push

#5961 ArmPkg: Disable AuditOnly mode for uncrustify
  ArmPkg/ArmPkg.ci.yaml
  ArmPkg/Library/ArmMonitorLib/ArmMonitorLib.c
  ArmPkg/Library/DebugPeCoffExtraActionLib/DebugPeCoffExtraActionLib.c
Labels: push

#5958 ArmPkg: Introduce ResetSystemLib implementation based on ArmMonitorLib
  ArmPkg/ArmPkg.dsc
  ArmPkg/Library/ArmPsciResetSystemLib/ArmPsciResetSystemLib.c
  ArmPkg/Library/ArmPsciResetSystemLib/ArmPsciResetSystemLib.inf
Labels: push

#5945 PrmPkg: Don't Set Access Attributes of Runtime MMIO Ranges
  PrmPkg/PrmConfigDxe/PrmConfigDxe.c
Labels: push, impact:security

#5960 UefiCpuPkg/MpInitLib: Reduce compiler dependencies for LoongArch
  UefiCpuPkg/Library/MpInitLib/LoongArch64/MpLib.c
Labels: push

#5941 ShellPkg: Add missing apps
  ShellPkg/ShellPkg.dsc
Labels: push

#5976 BaseTools/codeql: Update to CodeQL 2.18.1
  BaseTools/Plugin/CodeQL/codeqlcli_ext_dep.yaml
  BaseTools/Plugin/CodeQL/codeqlcli_linux_ext_dep.yaml
  BaseTools/Plugin/CodeQL/codeqlcli_windows_ext_dep.yaml
Labels: push

#5813 MdeModulePkg: Consume SOC related ACPI table from ACPI Silicon HOB
  MdeModulePkg/MdeModulePkg.dec
  MdeModulePkg/Universal/Acpi/AcpiTableDxe/AcpiTable.h
  MdeModulePkg/Universal/Acpi/AcpiTableDxe/AcpiTableDxe.inf
  MdeModulePkg/Universal/Acpi/AcpiTableDxe/AcpiTableProtocol.c
Labels: push

#5955 MdeModulePkg: Add NVMe Long Delay Time Events
  MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpress.h
  MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpressDxe.inf
  MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpressHci.c
  MdeModulePkg/Include/Guid/NVMeEventGroup.h
  MdeModulePkg/MdeModulePkg.dec
Labels: push

#5978 .azurepipelines: Disable the PR gate code coverage job
  .azurepipelines/templates/pr-gate-build-job.yml
Labels: push

#5973 .github/request-reviews.yml: Switch to pull_request_target
  .github/scripts/GitHub.py
  .github/workflows/request-reviews.yml
Labels: push

#5967 Pr retire armsmcpsciresetsystemlib
  ArmPkg/ArmPkg.dsc
  ArmPkg/Library/ArmSmcPsciResetSystemLib/ArmSmcPsciResetSystemLib.c
  ArmPkg/Library/ArmSmcPsciResetSystemLib/ArmSmcPsciResetSystemLib.inf
Labels: push

#5943 FmpDevicePkg: Assert on PcdFmpDeviceImageTypeIdGuid Size Mismatch
  FmpDevicePkg/FmpDxe/FmpDxe.c
Labels: push

#5991 BaseTools/tools_def CLANGDWARF: Always use -Oz in RELEASE mode
  BaseTools/Conf/tools_def.template
Labels: push

#5982 UefiCpuPkg: fix issue when SMM profile is enabled
  UefiCpuPkg/PiSmmCpuDxeSmm/SmmProfile.c
Labels: push

#5993 Fix issue in Pei/Variable.c
  MdeModulePkg/Universal/Variable/Pei/Variable.c
Labels: push

#5999 EmbeddedPkg: NonCoherentDmaLib: Set EFI_MEMORY_XP Capability on DMA Buffer
  EmbeddedPkg/Library/NonCoherentDmaLib/NonCoherentDmaLib.c
Labels: push

#5780 MdePkg: Update HEST Revision As 2
  MdePkg/Include/IndustryStandard/Acpi65.h
Labels: push

#6003 MdePkg: IORT header update for IORT Rev E.f spec
  MdePkg/Include/IndustryStandard/IoRemappingTable.h
Labels: push

#5984 BaseTools: fix build error with TOOL_CHAIN_TAG VS2015 & VS2015x86
  BaseTools/Conf/tools_def.template
  BaseTools/set_vsprefix_envs.bat
Labels: push

#5946 MdeModulePkg: NvmExpressDxe: Add Timeout Status Codes
  MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpressPassthru.c
Labels: push

#5986 BaseTools/Plugin/CodeQlQueries.qls: Pin to the 1.1.0 codeq/cpp-queries pack
  BaseTools/Plugin/CodeQL/CodeQlQueries.qls
  BaseTools/Plugin/CodeQL/codeqlcli_ext_dep.yaml
  BaseTools/Plugin/CodeQL/codeqlcli_linux_ext_dep.yaml
  BaseTools/Plugin/CodeQL/codeqlcli_windows_ext_dep.yaml
Labels: push
