Repository tianocore/edk2, pull requests merged in 2024-10, with the labels that each got.

#6252 .github/GitHub.py: Update bot in redundant comment check
  .github/scripts/GitHub.py
Labels: push

#6271 ArmVirtPkg/ArmVirtQemu: avoid unnecessary use of $(ARCH) conditional
  ArmVirtPkg/ArmVirtQemu.dsc
Labels: push

#6264 MdePkg: Improving readability of CVE patch for PeCoffLoaderRelocateImage
  MdePkg/Library/BasePeCoffLib/BasePeCoff.c
Labels: push

#6243 StandaloneMmPkg: CodeQL Fixes
  StandaloneMmPkg/Core/Dispatcher.c
  StandaloneMmPkg/Library/FvLib/FvLib.c
Labels: push

#5839 MdeModulePkg/UefiBootManagerLib: Build proper SD/MMC boot descriptions
  MdeModulePkg/Library/UefiBootManagerLib/BmBootDescription.c
  MdeModulePkg/Library/UefiBootManagerLib/InternalBm.h
Labels: push

#6201 MdePkg: Add CUSTOM_STACK_CHECK_LIB Macro
  MdePkg/Library/StackCheckLib/Readme.md
  MdePkg/MdeLibs.dsc.inc
Labels: push

#6269 ShellPkg/AcpiView: RAS2 Parser - Remove unused define
  ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Ras2/Ras2Parser.c
Labels: push

#6268 ShellPkg/AcpiView: RASF Parser
  ShellPkg/Library/UefiShellAcpiViewCommandLib/AcpiParser.h
  ShellPkg/Library/UefiShellAcpiViewCommandLib/Parsers/Rasf/RasfParser.c
  ShellPkg/Library/UefiShellAcpiViewCommandLib/UefiShellAcpiViewCommandLib.c
  ShellPkg/Library/UefiShellAcpiViewCommandLib/UefiShellAcpiViewCommandLib.inf
Labels: push

#5990 ShellPkg: ShellLevel2StripQuotes: Strip consecutive quotes
  ShellPkg/Library/UefiShellLevel2CommandsLib/UefiShellLevel2CommandsLib.c
Labels: push

#5971 ShellPkg: Fix Optional Data rewriting with bcfg
  ShellPkg/Library/UefiShellBcfgCommandLib/UefiShellBcfgCommandLib.c
Labels: push, impact:security

#6273 DynamicTablesPkg: Correct _PSD package format
  DynamicTablesPkg/Library/Common/AmlLib/CodeGen/AmlCodeGen.c
Labels: push

#6289 Maintainers.txt: Add myself as UefiPayloadPkg maintainer
  Maintainers.txt
Labels: push

#6284 DynamicTablesPkg: AmlLib: Fix CodeQL Issue
  DynamicTablesPkg/Library/Common/AmlLib/AmlEncoding/Aml.c
Labels: push

#6276 UnitTestFrameworkPkg: UnitTestLib: Support Failure Strings of 512 Chars
  UnitTestFrameworkPkg/Library/UnitTestLib/Assert.c
  UnitTestFrameworkPkg/Library/UnitTestLib/Log.c
  UnitTestFrameworkPkg/Library/UnitTestLib/UnitTestLib.c
  UnitTestFrameworkPkg/PrivateInclude/UnitTestFrameworkTypes.h
Labels: push

#6279 UefiPayloadPkg : Roll back the sequence of gEfiEndOfPeiSignalPpiGuid.
  UefiPayloadPkg/PayloadLoaderPeim/FitPayloadLoaderPeim.c
Labels: push

#6281 FmpDevicePkg/FmpDependencyLib: Fix potential overflow in loop
  FmpDevicePkg/Library/FmpDependencyLib/FmpDependencyLib.c
Labels: push

#6259 BaseTools/CodeQl: Give preference to Plugin settings
  BaseTools/Plugin/CodeQL/CodeQlAnalyzePlugin.py
Labels: push

#6258 BaseTools/SetupGit.py: Fix invalid choice 'edk2-test'
  BaseTools/Scripts/SetupGit.py
Labels: push

#6222 UefiPayloadPkg: Add Secure Boot support
  UefiPayloadPkg/UefiPayloadPkg.ci.yaml
  UefiPayloadPkg/UefiPayloadPkg.dsc
  UefiPayloadPkg/UefiPayloadPkg.fdf
  UefiPayloadPkg/UniversalPayloadBuild.py
Labels: push

#6293 DynamicTablesPkg: Update FADT fixed feature flags validation
  DynamicTablesPkg/Library/Acpi/Common/AcpiFadtLib/FadtGenerator.c
Labels: push

#6227 NetworkPkg/HttpBootDxe: Report download error when resume attempts fail
  NetworkPkg/HttpBootDxe/HttpBootImpl.c
Labels: push

#6317 UefiCpuPkg/PiSmmCpuDxeSmm: Save and restore CR2 only if SmiProfile en…
  UefiCpuPkg/PiSmmCpuDxeSmm/X64/PageTbl.c
Labels: push

#6288 ArmPkg: CodeQL Fixes.
  ArmPkg/Drivers/ArmGic/ArmGicLib.c
  ArmPkg/Include/Library/ArmGicLib.h
Labels: push

#6333 USB Association Descriptor Definitions
  MdePkg/Include/IndustryStandard/Usb.h
Labels: push

#6335 UnitTestFrameworkPkg: VS2022 Support on UnitTest.
  UnitTestFrameworkPkg/UnitTestFrameworkPkgHost.dsc.inc
Labels: push

#6297 edksetup.sh: Fix the Issue of PYTHON_COMMAND Un-Configurable
  edksetup.sh
Labels: push, impact:testing

#6329 MdePkg/Include/Guid: Add missing CXL definitions to Cper.h
  MdePkg/Include/Guid/Cper.h
Labels: push

#6302 MdeModulePkg: Fix PeiAllocatePages() corner case
  MdeModulePkg/Core/Pei/Memory/MemoryServices.c
Labels: push

#6233 MdePkg: Create Google Test mock library and protocol
  MdePkg/Test/MdePkgHostTest.dsc
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockCpuLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockPciSegmentLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockReportStatusCodeLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockSmmServicesTableLib.h
  MdePkg/Test/Mock/Include/GoogleTest/Protocol/MockMpService.h
  MdePkg/Test/Mock/Library/GoogleTest/MockCpuLib/MockCpuLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockCpuLib/MockCpuLib.inf
  MdePkg/Test/Mock/Library/GoogleTest/MockPciSegmentLib/MockPciSegmentLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockPciSegmentLib/MockPciSegmentLib.inf
  MdePkg/Test/Mock/Library/GoogleTest/MockReportStatusCodeLib/MockReportStatusCodeLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockReportStatusCodeLib/MockReportStatusCodeLib.inf
  MdePkg/Test/Mock/Library/GoogleTest/MockSmmServicesTableLib/MockSmmServicesTableLib.cpp
  MdePkg/Test/Mock/Library/GoogleTest/MockSmmServicesTableLib/MockSmmServicesTableLib.inf
Labels: push, impact:testing

#6353 MdePkg/Include/Guid: Rename CXL definitions in Cper.h to include EFI_ prefix
  MdePkg/Include/Guid/Cper.h
Labels: push

#6352 ShellPkg/SmbiosView: Correct wrong length offset usage in SMBIOS Type4
  ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.c
Labels: push

#6336 USB Class specific definitions
  MdeModulePkg/Bus/Usb/UsbNetwork/UsbCdcEcm/UsbEcmFunction.c
  MdeModulePkg/Bus/Usb/UsbNetwork/UsbCdcNcm/UsbNcmFunction.c
  MdeModulePkg/Bus/Usb/UsbNetwork/UsbRndis/UsbRndisFunction.c
  MdeModulePkg/Include/Protocol/UsbEthernetProtocol.h
Labels: push

#6358 DynamicTablesPkg: Update creator id for WSMT table
  DynamicTablesPkg/Library/Acpi/X64/AcpiWsmtLib/WsmtGenerator.c
Labels: push

#6348 Update CI config following CompilerIntrinsicsLib move from ArmPkg
  ArmPkg/ArmPkg.ci.yaml
Labels: push

#6361 DynamicTablesPkg: Update X64 FADT XPm1aEvtBlk
  DynamicTablesPkg/Library/Acpi/Common/AcpiFadtLib/X64/X64FadtGenerator.c
Labels: push

#6365 MdePkg/Include/Guid: Fix EFI_CXL_COMPONENT_EVENT_LOG in Cper.h
  MdePkg/Include/Guid/Cper.h
Labels: push

#6355 BaseTools/GenFw X64: Detect GOTCPRELX relaxations applied by LLD
  BaseTools/Source/C/GenFw/Elf64Convert.c
Labels: push

#6367 DynamicTablesPkg: Fix the comparision by using correct max value of U…
  DynamicTablesPkg/Library/Common/AmlLib/CodeGen/AmlResourceDataCodeGen.c
Labels: push

#6278 .pytool/UncrustifyCheck: Add a in-place option
  .pytool/Plugin/UncrustifyCheck/Readme.md
  .pytool/Plugin/UncrustifyCheck/UncrustifyCheck.py
Labels: push

#6031 MdeModulePkg/PciHostBridgeDxe: Add MemoryFence after write.
  MdeModulePkg/Bus/Pci/PciHostBridgeDxe/PciRootBridgeIo.c
Labels: push

#6280 FatPkg: Fix potentially uninitialized variable
  FatPkg/EnhancedFatDxe/Info.c
  FatPkg/FatPei/FatLiteApi.c
Labels: push

#6360 MdeModulePkg/TerminalDxe: Return success if device not support SetControl
  MdeModulePkg/Universal/Console/TerminalDxe/TerminalConIn.c
Labels: push

#6340 MdeModulePkg: Added PPI support in UFS PEI driver.
  MdeModulePkg/Bus/Ufs/UfsBlockIoPei/UfsBlockIoPei.c
  MdeModulePkg/Bus/Ufs/UfsBlockIoPei/UfsBlockIoPei.h
  MdeModulePkg/Bus/Ufs/UfsBlockIoPei/UfsBlockIoPei.inf
  MdeModulePkg/Bus/Ufs/UfsBlockIoPei/UfsHci.c
  MdeModulePkg/Include/Ppi/UfsHostControllerPlatformPpi.h
  MdeModulePkg/MdeModulePkg.dec
Labels: push

#6344 MdePkg/MockUefiLib: Added new mock functions.
  MdePkg/Test/Mock/Include/GoogleTest/Library/MockUefiLib.h
  MdePkg/Test/Mock/Library/GoogleTest/MockUefiLib/MockUefiLib.cpp
Labels: push

#6250 IntelFsp2WrapperPkg: Prevent null pointer dereference
  IntelFsp2WrapperPkg/FspsWrapperPeim/FspsWrapperPeim.c
Labels: push

#6080 EmulatorPkg/Win/Host: Source level debugging on already loaded DLL
  EmulatorPkg/Win/Host/WinHost.c
Labels: push

#6349 StandaloneMmPkg/Core: Reset IsCommBufferValid to FALSE before MMI exits
  StandaloneMmPkg/Core/StandaloneMmCore.c
Labels: push, impact:breaking-change

#6256 UefiCpuPkg/PiSmmCpuDxeSmm: Fix extraneous parentheses
  UefiCpuPkg/PiSmmCpuDxeSmm/NonMmramMapDxeSmm.c
Labels: push

#6351 StandaloneMmPkg/Core: Shadow Standalone BFV into MMRAM
  StandaloneMmPkg/Core/Dispatcher.c
  StandaloneMmPkg/Core/StandaloneMmCore.c
  StandaloneMmPkg/Core/StandaloneMmCore.h
  StandaloneMmPkg/Drivers/StandaloneMmIplPei/StandaloneMmIplPei.c
Labels: push

#6374 MdeModulePkg: adding support for authenticated variable storage data format
  MdeModulePkg/Universal/HiiDatabaseDxe/Database.c
  MdeModulePkg/Universal/HiiDatabaseDxe/HiiDatabaseDxe.inf
Labels: push

#6328 UefiCpuPkg/MmUnblockMemoryLib: Check if buffer range is valid
  UefiCpuPkg/Library/MmUnblockMemoryLib/MmUnblockMemoryLib.c
Labels: push

#6384 Maintainers: Revert "Remove Ard Biesheuvel from all packages"
  Maintainers.txt
Labels: push

#6376 ArmVirtPkg: KvmTool: Fix clang linker error
  ArmVirtPkg/ArmVirtKvmTool.dsc
Labels: push

#6308 ArmPlatformPkg: CodeQL Fixes.
  ArmPlatformPkg/Drivers/LcdGraphicsOutputDxe/LcdGraphicsOutputBlt.c
  ArmPlatformPkg/Drivers/PL061GpioDxe/PL061Gpio.c
  ArmPlatformPkg/Drivers/PL061GpioDxe/PL061Gpio.h
  ArmPlatformPkg/Drivers/SP805WatchdogDxe/SP805Watchdog.c
  ArmPlatformPkg/Library/PL111Lcd/PL111Lcd.h
Labels: push

#6316 Correct max physical address bit
  StandaloneMmPkg/Drivers/StandaloneMmIplPei/MmFoundationHob.c
Labels: push
