Repository tianocore/edk2, pull requests merged in 2024-06, with the labels that each got.

#5691 MdeModulePkg: Update GCD attribute conversion to support SP attribute
  MdeModulePkg/Core/Dxe/Gcd/Gcd.c
Labels: push

#5693 CryptoPkg/BaseCryptLib: Enable more functions for SMM/StandaloneMM
  CryptoPkg/Library/BaseCryptLib/SmmCryptLib.inf
Labels: push

#5392 Fix page split isuue in cpupagetablelib
  UefiCpuPkg/Library/CpuPageTableLib/CpuPageTableMap.c
Labels: push

#5718 MdeModulePkg/HiiDatabaseDxe: Avoid struct assignment
  MdeModulePkg/Universal/HiiDatabaseDxe/Image.c
Labels: push

#5724 Adding definitions for Ipmi Net Sensor Get/Set Thresholds commands
  MdePkg/Include/IndustryStandard/IpmiNetFnSensorEvent.h
Labels: push

#5742 ArmVirtPkg: Remove the NorFlashQemuLib
  ArmVirtPkg/Library/NorFlashQemuLib/NorFlashQemuLib.c
  ArmVirtPkg/Library/NorFlashQemuLib/NorFlashQemuLib.inf
Labels: push

#5731 OvmfPkg: add morlock support
  OvmfPkg/Include/Dsc/MorLock.dsc.inc
  OvmfPkg/Include/Fdf/MorLock.fdf.inc
  OvmfPkg/OvmfPkgIa32.dsc
  OvmfPkg/OvmfPkgIa32.fdf
  OvmfPkg/OvmfPkgIa32X64.dsc
  OvmfPkg/OvmfPkgIa32X64.fdf
  OvmfPkg/OvmfPkgX64.dsc
  OvmfPkg/OvmfPkgX64.fdf
Labels: push, impact:security

#5725 MdeModulePkg/HiiDatabaseDxe: Remove assert for VarStoreId = 0
  MdeModulePkg/Universal/HiiDatabaseDxe/ConfigKeywordHandler.c
Labels: push

#5733 OvmfPkg/PlatformInitLib: add support for GuestPhysBits
  OvmfPkg/Library/PlatformInitLib/MemDetect.c
Labels: push

#5730 CryptoPkg: Fix wrong logic in X509GetTBSCert
  CryptoPkg/Library/BaseCryptLib/Pk/CryptX509.c
Labels: push

#5752 BaseTools/Scripts: Fix PatchCheck commit range
  BaseTools/Scripts/PatchCheck.py
Labels: push

#5729 MdeModulePkg: Warn if out of flash space when writing variables
  MdeModulePkg/Universal/Variable/RuntimeDxe/Variable.c
Labels: push

#5685 ShellPkg/Pci.c: Update supported link speed to PCIe Gen6
  ShellPkg/Library/UefiShellDebug1CommandsLib/Pci.c
Labels: push

#5700 MdeModulePkg: In RemoveTableFromRsdt don't read from unallocated memory
  MdeModulePkg/Universal/Acpi/AcpiTableDxe/AcpiTableProtocol.c
Labels: push

#5734 CryptoPkg: Fix BaseCryptLib CrtWrapper strcpy/strncpy/strcat
  CryptoPkg/Library/BaseCryptLib/SysCall/CrtWrapper.c
  CryptoPkg/Library/Include/CrtLibSupport.h
Labels: push

#5692 MdeModulePkg/DxeCapsuleLibFmp: Fix crash if no ESRT is found
  MdeModulePkg/Library/DxeCapsuleLibFmp/DxeCapsuleLib.c
  MdeModulePkg/Library/DxeCapsuleLibFmp/DxeCapsuleRuntime.c
Labels: push

#5750 OvmfPkg/QemuVideoDxe: purge VbeShim
  OvmfPkg/QemuVideoDxe/Driver.c
  OvmfPkg/QemuVideoDxe/Qemu.h
  OvmfPkg/QemuVideoDxe/QemuVideoDxe.inf
  OvmfPkg/QemuVideoDxe/VbeShim.asm
  OvmfPkg/QemuVideoDxe/VbeShim.c
  OvmfPkg/QemuVideoDxe/VbeShim.h
  OvmfPkg/QemuVideoDxe/VbeShim.sh
Labels: push

#5732 UefiPayloadPkg: Fix LoadDxeCore for payload size > 16MB
  UefiPayloadPkg/UefiPayloadEntry/LoadDxeCore.c
Labels: push

#5763 MdePkg/BaseLib: Let CpuDeadLoop() be breakable in debugger
  MdePkg/Library/BaseLib/CpuDeadLoop.c
Labels: push

#5759 OvmfPkg/Xen: Fix use of networking
  OvmfPkg/OvmfXen.dsc
  OvmfPkg/OvmfXen.fdf
Labels: push

#5777 ArmPkg/CompilerIntrinsicsLib: provide __ashlti3
  ArmPkg/Library/CompilerIntrinsicsLib/AArch64/ashlti3.S
  ArmPkg/Library/CompilerIntrinsicsLib/CompilerIntrinsicsLib.inf
Labels: push

#5778 BaseTools/BuildReport: Improve compile_commands generation
  BaseTools/Source/Python/build/BuildReport.py
Labels: push

#5773 CryptoPkg: Fix strncpy for BaseCryptLibMbedTls
  CryptoPkg/Library/BaseCryptLibMbedTls/SysCall/DummyOpensslSupport.c
Labels: push

#5583 UefiCpuPkg/SmmCpuSyncLib: Add MM_STANDALONE tag.
  UefiCpuPkg/Library/SmmCpuSyncLib/SmmCpuSyncLib.inf
Labels: push

#5776 ArmPkg/ProcessorSubClassDxe: Limit values to 0xFF
  ArmPkg/Universal/Smbios/ProcessorSubClassDxe/ProcessorSubClass.c
Labels: push

#5783 MdeModulePkg/Core/Pei: Install MigrateTempRamPpi
  MdeModulePkg/Core/Pei/PeiMain.h
  MdeModulePkg/Core/Pei/PeiMain.inf
  MdeModulePkg/Core/Pei/PeiMain/PeiMain.c
  MdeModulePkg/Include/Guid/MigratedFvInfo.h
  MdeModulePkg/Include/Ppi/MigrateTempRam.h
  MdeModulePkg/MdeModulePkg.dec
Labels: push

#5782 .devcontainer: bump Fedora version to 39
  .devcontainer/devcontainer.json
Labels: push

#5790 OvmfPkg/BhyvePkg: honor FwCfg when setting the bootorder
  OvmfPkg/Bhyve/BhyveX64.dsc
  OvmfPkg/Library/PlatformBootManagerLibBhyve/BdsPlatform.c
  OvmfPkg/Library/PlatformBootManagerLibBhyve/PlatformBootManagerLibBhyve.inf
Labels: push

#5786 OvmfPkg/QemuVideoDxe: add feature PCD to remap framebuffer W/C
  OvmfPkg/OvmfPkg.dec
  OvmfPkg/QemuVideoDxe/Gop.c
  OvmfPkg/QemuVideoDxe/Qemu.h
  OvmfPkg/QemuVideoDxe/QemuVideoDxe.inf
Labels: push

#5791 MdeModulePkg/DxeCapsuleLibFmp: Fix compilation error
  MdeModulePkg/Library/DxeCapsuleLibFmp/DxeCapsuleLib.c
  MdeModulePkg/Library/DxeCapsuleLibFmp/DxeCapsuleRuntime.c
Labels: push

#5760 MdeModulePkg: Avoid efi memory allocation for SP type
  MdeModulePkg/Core/Dxe/Mem/Page.c
Labels: push

#5486 UefiCpuPkg: Correct the count of different type of Cache.
  UefiCpuPkg/Library/CpuCacheInfoLib/CpuCacheInfoLib.c
Labels: push

#5798 Refine td tcg2 dxe
  OvmfPkg/Tcg/TdTcg2Dxe/TdTcg2Dxe.c
  OvmfPkg/Tcg/TdTcg2Dxe/TdTcg2Dxe.inf
Labels: push

#5769 AmdSev: Harden SEV Kernel hashes verifier
  OvmfPkg/AmdSev/BlobVerifierLibSevHashes/BlobVerifierSevHashes.c
  OvmfPkg/Include/Library/BlobVerifierLib.h
  OvmfPkg/Library/BlobVerifierLibNull/BlobVerifierNull.c
  OvmfPkg/QemuKernelLoaderFsDxe/QemuKernelLoaderFsDxe.c
Labels: push

#5735 CryptoPkg: Add SNI extension to TLS ClientHello
  CryptoPkg/Library/TlsLib/TlsConfig.c
Labels: push

#5755 CryptoPkg: Extend TLS handshake debug output
  CryptoPkg/Library/TlsLib/TlsProcess.c
Labels: push

#5800 ReadMe.rst: Add mbedtls submodule license
  ReadMe.rst
Labels: push

#5803 CryptoPkg: Fix wrong comment for CryptoPkg
  CryptoPkg/Include/Library/BaseCryptLib.h
  CryptoPkg/Library/BaseCryptLib/Pk/CryptX509.c
  CryptoPkg/Library/BaseCryptLibMbedTls/InternalCryptLib.h
  CryptoPkg/Library/BaseCryptLibMbedTls/Pk/CryptPkcs7VerifyEku.c
  CryptoPkg/Library/BaseCryptLibMbedTls/Pk/CryptX509.c
  CryptoPkg/Library/BaseCryptLibMbedTls/Pk/CryptX509Null.c
  CryptoPkg/Library/BaseCryptLibMbedTls/Rand/CryptRand.c
  CryptoPkg/Library/BaseCryptLibMbedTls/Rand/CryptRandTsc.c
Labels: push

#5811 MdeModulePkg/ImagePropertiesRecordLib: Reduce debug level
  MdeModulePkg/Library/ImagePropertiesRecordLib/ImagePropertiesRecordLib.c
Labels: push

#5788 MdeModulePkg/DisplayEngineDxe: Support "^" and "V" key on pop-up form
  MdeModulePkg/Universal/DisplayEngineDxe/InputHandler.c
Labels: push

#5795 NetworkPkg/DxeNetLib: adjust PseudoRandom error logging
  NetworkPkg/Library/DxeNetLib/DxeNetLib.c
Labels: push

#5831 BaseTools: BinToPcd: Remove xdrlib dependency
  BaseTools/Scripts/BinToPcd.py
Labels: push, python
