Repository tianocore/edk2, pull requests merged in 2025-07, with the labels that each got.

#11238 UefiCpuPkg/PiSmmCpuDxeSmm: Add sync barrier before BSP invokes SmmCor…
  UefiCpuPkg/PiSmmCpuDxeSmm/MpService.c
Labels: push

#11250 CryptoPkg: Enable the time check flag.
  CryptoPkg/Library/TlsLib/TlsInit.c
Labels: push

#11219 OvmfPkg: Pass command-line args to PR Eval
  OvmfPkg/PlatformCI/PlatformBuildLib.py
Labels: push

#11231 EmbeddedPkg/PrePiMemoryAllocationLib: Add reserved memory allocations
  EmbeddedPkg/Library/PrePiMemoryAllocationLib/MemoryAllocationLib.c
Labels: push

#11223 OvmfPkg/PlatformDxe: register log buffer as efi config table
  OvmfPkg/PlatformDxe/Platform.c
  OvmfPkg/PlatformDxe/Platform.inf
Labels: push

#11086 MdeModulePkg: Leak Memory if Not RW on FreePages
  MdeModulePkg/Core/Dxe/DxeMain.h
  MdeModulePkg/Core/Dxe/DxeMain.inf
  MdeModulePkg/Core/Dxe/Mem/Page.c
  MdeModulePkg/Core/Dxe/Misc/MemoryProtection.c
Labels: push

#11265 BaseTools/toolsetup.bat: Set IASL_PREFIX when using Mingw-w64 on Windows
  BaseTools/set_vsprefix_envs.bat
  BaseTools/toolsetup.bat
Labels: push

#11266 CryptoPkg: Add support for IA32 builds using CLANGPDB
  CryptoPkg/Library/IntrinsicLib/Ia32/MathUlldiv.nasm
  CryptoPkg/Library/IntrinsicLib/IntrinsicLib.inf
Labels: push

#11303 Maintainers.txt: Update reviewer for OvmfPkg/Confidential Computing
  Maintainers.txt
Labels: push

#11309 OvmfPkg/LoongArchVirt: Add SATA support
  OvmfPkg/LoongArchVirt/LoongArchVirtQemu.dsc
  OvmfPkg/LoongArchVirt/LoongArchVirtQemu.fdf
Labels: push

#11068 MdeModulePkg: FvSimpleFileSystemDxe cumulative codeql issues.
  MdeModulePkg/Universal/FvSimpleFileSystemDxe/FvSimpleFileSystem.c
  MdeModulePkg/Universal/FvSimpleFileSystemDxe/FvSimpleFileSystemEntryPoint.c
Labels: stale

#11064 MdeModulePkg: Console cumulative codeql issues.
  MdeModulePkg/Universal/Console/ConPlatformDxe/ConPlatform.c
  MdeModulePkg/Universal/Console/GraphicsConsoleDxe/GraphicsConsole.c
  MdeModulePkg/Universal/Console/TerminalDxe/Terminal.c
Labels: push, stale

#11317 Smm cpu wait all aps fix
  UefiCpuPkg/PiSmmCpuDxeSmm/MpService.c
Labels: push

#11283 MdePkg: Add RISC-V specific structure definitions in Acpi66.h
  MdePkg/Include/IndustryStandard/Acpi66.h
Labels: push

#11312 EmbeddedPkg: Fix incorrect define for hardware interrupt2 protocol
  EmbeddedPkg/Include/Protocol/HardwareInterrupt2.h
Labels: push

#11328 ShellPkg: Shell Validate parameter before use.
  ShellPkg/Application/Shell/Shell.c
Labels: push

#11334 SecurityPkg: Tpm2DumpLib: Make All Prints at DEBUG_SECURITY
  SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2DeviceLibDTpmDump.c
Labels: push

#11307 SecurityPkg: CodeQL Fixes
  SecurityPkg/FvReportPei/FvReportPei.c
  SecurityPkg/HddPassword/HddPasswordDxe.c
  SecurityPkg/Library/AuthVariableLib/AuthService.c
  SecurityPkg/Library/DxeImageVerificationLib/DxeImageVerificationLib.c
  SecurityPkg/Library/DxeTcg2PhysicalPresenceLib/DxeTcg2PhysicalPresenceLib.c
  SecurityPkg/Library/DxeTcgPhysicalPresenceLib/DxeTcgPhysicalPresenceLib.c
  SecurityPkg/Library/DxeTpm2MeasureBootLib/DxeTpm2MeasureBootLib.c
  SecurityPkg/Library/HashInstanceLibSha1/HashInstanceLibSha1.c
  SecurityPkg/Library/HashInstanceLibSha256/HashInstanceLibSha256.c
  SecurityPkg/Library/HashLibBaseCryptoRouter/HashLibBaseCryptoRouterDxe.c
  SecurityPkg/Library/HashLibBaseCryptoRouter/HashLibBaseCryptoRouterPei.c
  SecurityPkg/Library/SecureBootVariableProvisionLib/SecureBootVariableProvisionLib.c
  SecurityPkg/Library/TcgEventLogRecordLib/TcgEventLogRecordLib.c
  SecurityPkg/Library/Tpm12DeviceLibDTpm/Tpm12Tis.c
  SecurityPkg/RandomNumberGenerator/RngDxe/Rand/AesCore.c
  SecurityPkg/Tcg/Opal/OpalPassword/OpalDriver.c
  SecurityPkg/Tcg/Opal/OpalPassword/OpalHii.c
  SecurityPkg/Tcg/Tcg2Config/Tcg2ConfigDriver.c
  SecurityPkg/Tcg/Tcg2Dxe/Tcg2Dxe.c
  SecurityPkg/Tcg/TcgConfigDxe/TcgConfigImpl.c
  SecurityPkg/Tcg/TcgDxe/TcgDxe.c
  SecurityPkg/VariableAuthenticated/SecureBootConfigDxe/SecureBootConfigFileExplorer.c
  SecurityPkg/VariableAuthenticated/SecureBootConfigDxe/SecureBootConfigImpl.c
Labels: push, impact:security

#11302 ShellPkg: Fix Dead Code and Null field Coverity warnings.
  ShellPkg/Application/Shell/ShellEnvVar.c
  ShellPkg/Application/Shell/ShellProtocol.c
  ShellPkg/Library/UefiShellCommandLib/UefiShellCommandLib.c
  ShellPkg/Library/UefiShellDebug1CommandsLib/SmbiosView/PrintInfo.c
Labels: push

#11174 CloudHv: bump PcdCpuMaxLogicalProcessorNumber to 254
  OvmfPkg/CloudHv/CloudHvX64.dsc
Labels: push
