Repository tianocore/edk2, pull requests merged in 2025-03, with the labels that each got.

#10770 MdeModulePkg/TerminalDxe: Support multiple modes for SetMode function
  MdeModulePkg/Universal/Console/TerminalDxe/Terminal.c
  MdeModulePkg/Universal/Console/TerminalDxe/Terminal.h
  MdeModulePkg/Universal/Console/TerminalDxe/TerminalConOut.c
Labels: push

#10644 SecurityPkg: fix possible out of bond array access in debug traces
  SecurityPkg/Library/Tpm12DeviceLibDTpm/Tpm12Tis.c
  SecurityPkg/Library/Tpm2DeviceLibDTpm/Tpm2Tis.c
Labels: push

#10808 CryptoPkg: Add sleep function to BaseCryptLibMbedTls Timerwrapper
  CryptoPkg/Library/BaseCryptLibMbedTls/SysCall/TimerWrapper.c
Labels: push

#10780 MdeModulePkg/DxeCapsuleLibFmp: Check for NULL in IsValidCapsuleHeader
  MdeModulePkg/Library/DxeCapsuleLibFmp/DxeCapsuleLib.c
Labels: push

#10822 ArmPkg/ArmTransferListLib: improve coding style compliance
  ArmPkg/Include/Library/ArmTransferListLib.h
  ArmPkg/Library/ArmStandaloneMmCoreEntryPoint/ArmStandaloneMmCoreEntryPoint.c
  ArmPkg/Library/ArmTransferListLib/ArmTransferListLib.c
Labels: push, impact:breaking-change

#10824 DebugMacroCheck: Do not show progress bar with zero items
  BaseTools/Plugin/DebugMacroCheck/DebugMacroCheck.py
Labels: push

#10795 pip-requirements.txt: Update pip modules
  pip-requirements.txt
Labels: push

#10634 Bug xxx crypto pkg openssl clang asm file fix
  CryptoPkg/CryptoPkg.dec
  CryptoPkg/CryptoPkg.dsc
  CryptoPkg/CryptoPkgFeatureFlagPcds.dsc.inc
  CryptoPkg/Library/IntrinsicLib/IntrinsicLib.inf
  CryptoPkg/Library/IntrinsicLib/Math.c
  CryptoPkg/Library/OpensslLib/OpensslLib.inf
  CryptoPkg/Library/OpensslLib/OpensslLibAccel.inf
  CryptoPkg/Library/OpensslLib/OpensslLibCrypto.inf
  CryptoPkg/Library/OpensslLib/OpensslLibFull.inf
  CryptoPkg/Library/OpensslLib/OpensslLibFullAccel.inf
  CryptoPkg/Library/OpensslLib/configure.py
  CryptoPkg/Test/CryptoPkgHostUnitTest.dsc
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestBaseCryptLib.h
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestBaseCryptLibHost.inf
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/UnitTestMain.c
  CryptoPkg/Test/UnitTest/Library/BaseCryptLib/UnitTestMainHost.c
Labels: push, impact:breaking-change

#10831 OvmfPkg/PlatformInitLib: fix typo
  OvmfPkg/Library/PlatformInitLib/MemDetect.c
Labels: push

#10816 MdePkg: fix fru device description string copy error.
  MdePkg/Include/IndustryStandard/IpmiNetFnStorage.h
Labels: push

#10830 UnitTestFrameworkPkg: Fix host test /WHOLEARCHIVE regression
  UnitTestFrameworkPkg/UnitTestFrameworkPkgHost.dsc.inc
Labels: push

#10835 StandaloneMmPkg/Library: Print warning message if GUID HOB not found
  StandaloneMmPkg/Library/StandaloneMmHobLib/StandaloneMmHobLib.c
Labels: push

#10842 BaseTools/Source/C: Disable VS flexible array member warning
  BaseTools/Source/C/Makefiles/ms.common
Labels: push

#10800 DynamicTablesPkg: Resolve cppcheck findings in macros
  DynamicTablesPkg/Include/ConfigurationManagerObject.h
  DynamicTablesPkg/Include/TableGenerator.h
Labels: push

#10799 DynamicTablesPkg: Tolerate NULL when freeing MADT table
  DynamicTablesPkg/Library/Acpi/Arm/AcpiMadtLibArm/MadtGenerator.c
Labels: push

#10846 Editing maintainers list
  Maintainers.txt
Labels: push

#10826 MdePkg: Add ACPI CEDT table structures
  MdePkg/Include/IndustryStandard/Acpi64.h
Labels: push

#10844 CapsuleApp: Fix proper return after capsule update
  MdeModulePkg/Application/CapsuleApp/CapsuleApp.c
Labels: push

#10849 Maintainers.txt: Transfer Ray's Reviewer role to Dandan
  Maintainers.txt
Labels: push

#10793 DynamicTablesPkg/AcpiSsdtCpuTopologyLib: Correct _STA method for X64
  DynamicTablesPkg/Library/Acpi/Common/AcpiSsdtCpuTopologyLib/X64/X64SsdtCpuTopologyGenerator.c
Labels: push

#10850 OvmfPkg/HardwareInfoLib: Reserve device type ID for SVSM
  OvmfPkg/Library/HardwareInfoLib/HardwareInfoTypesLib.h
Labels: push

#10845 UefiPayloadPkg: Skip PCI RB Segment parsing if no RB semgment info provided
  UefiPayloadPkg/Library/FdtParserLib/FdtParserLib.c
Labels: push

#10857 UnitTestFrameworkPkg: Avoid duplicate library function names
  UnitTestFrameworkPkg/Library/UnitTestPeiServicesTablePointerLib/UnitTestPeiServicesTablePointerLib.c
  UnitTestFrameworkPkg/Library/UnitTestPeiServicesTablePointerLib/UnitTestPeiServicesTablePointerLib.h
  UnitTestFrameworkPkg/Library/UnitTestPeiServicesTablePointerLib/UnitTestPeiServicesTablePointerLibMisc.c
Labels: push

#10801 StandaloneMmPkg: Remove Assert when gMmCommBufferHobGuid does not exist.
  StandaloneMmPkg/Core/StandaloneMmCore.c
Labels: push

#10852 .mergify: Use tianocore-issues to rebase PRs for merge
  .mergify/config.yml
Labels: push

#10863 NetworkPkg/IScsiDxe:Fix for Remote Memory Exposure in ISCSI bz4206
  NetworkPkg/IScsiDxe/IScsiProto.c
Labels: push

#10829 MdeModulePkg/XhciDxe: Adjust out-of-range bInterval values
  MdeModulePkg/Bus/Pci/XhciDxe/XhciSched.c
Labels: push

#6428 ArmPkg: Create DxeMmReadyToLockProtocol notification
  ArmPkg/Drivers/MmCommunicationDxe/MmCommunication.c
  ArmPkg/Drivers/MmCommunicationDxe/MmCommunication.inf
Labels: push

#10758 MdeModulePkg: address VarCheckHiiLib build failures
  MdeModulePkg/Library/VarCheckHiiLib/VarCheckHiiLibStandaloneMm.c
Labels: push

#10870 Maintainers.txt: Add Shuo Liu as UefiPayloadPkg Reviewer
  Maintainers.txt
Labels: push

#10877 Maintainers.txt: Add SweeAun as StandaloneMmPkg reviewer
  Maintainers.txt
Labels: push

#10862 MdePkg: IndustryStandard: Rename ACPI SPCR revision 4 structure
  MdePkg/Include/IndustryStandard/SerialPortConsoleRedirectionTable.h
Labels: push, impact:breaking-change

#10737 UefiCpuPkg MpInformation2.h: Include PiMultiPhase.h
  UefiCpuPkg/Include/Guid/MpInformation2.h
Labels: push

#10828 BaseTools/GenFv: Ensure the minimum pad file size for the FV with VTF
  BaseTools/Source/C/GenFv/GenFvInternalLib.c
Labels: push

#10847 BaseTools: Fix missing module PCD in compile information of build report
  BaseTools/Source/Python/build/BuildReport.py
Labels: push

#10885 MdeModulePkg/DxeCorePerformanceLib: Fix incorrect size calculation
  MdeModulePkg/Library/DxeCorePerformanceLib/DxeCorePerformanceLib.c
Labels: push

#10865 BaseTools/FMMT: Fix the GUID Tool Not Found the Shell Script Issue
  BaseTools/Source/Python/FMMT/core/GuidTools.py
Labels: push, impact:testing

#10875 PrmPkg: Correct the flags for GCC compiler
  PrmPkg/Samples/PrmSampleAcpiParameterBufferModule/PrmSampleAcpiParameterBufferModule.inf
  PrmPkg/Samples/PrmSampleContextBufferModule/PrmSampleContextBufferModule.inf
Labels: push

#10784 MdeModulePkg/Core: Add Hot Pluggable type to Attribute Conversion Table
  MdeModulePkg/Core/Dxe/Gcd/Gcd.c
Labels: push

#10903 BaseTools/build: Reduce special FV full to warning
  BaseTools/Source/Python/build/build.py
Labels: push

#10890 StandaloneMmCorePerformanceLib.inf: Add gEfiEventExitBootServicesGuid
  MdeModulePkg/Library/SmmCorePerformanceLib/StandaloneMmCorePerformanceLib.inf
Labels: push
